ARG REPOSITORY=openfaas/faas-cli
ARG VERSION=0.7.0
ARG FILE_SHA256SUM=98cbd98e6850ec3e29f9b8384dd157dfff144af62af7af7be09260ea337f8673
ENV FILE_URL https://github.com/${REPOSITORY}/releases/download/${VERSION}/faas-cli
