ARG REPOSITORY=openfaas/faas-cli
ARG VERSION=0.6.20
ARG FILE_SHA256SUM=abeeb52919c0d368136378f0dfa069d7f219f3c53dc8f0ccb13eb7be6364dd9f
ENV FILE_URL https://github.com/${REPOSITORY}/releases/download/${VERSION}/faas-cli
