ARG REPOSITORY=docker/compose
ARG VERSION=1.23.2
ARG FILE_SHA256SUM=5cec8b883c26f00e45f472c6024f4d367e555c8f48956220bdb16f0298798452
ENV FILE_URL https://raw.githubusercontent.com/${REPOSITORY}/${VERSION}/contrib/completion/bash/docker-compose
