ARG REPOSITORY=docker/compose
ARG VERSION=1.21.2
ARG FILE_SHA256SUM=618ef7a88b4090a5e5708b5f44b18b3c811d8d6c98465977aa64fde39c6e7455
ENV FILE_URL https://raw.githubusercontent.com/${REPOSITORY}/${VERSION}/contrib/completion/bash/docker-compose
