ARG REPOSITORY=docker/compose
ARG VERSION=1.18
ARG FILE_SHA256SUM=4cef666a7e0160c1be300d18b398852de662e12265c1cab2eb585e8bbf173102
ENV FILE_URL https://raw.githubusercontent.com/${REPOSITORY}/${VERSION}/contrib/completion/bash/docker-compose
