ARG REPOSITORY=docker/app
ARG VERSION=0.3.0
ARG FILE_SHA256SUM=9e97ba66e67b2f00399278acbc2a49f25a00a7e65eeb3a555153445f2d345314
ENV FILE_URL https://github.com/${REPOSITORY}/releases/download/v${VERSION}/docker-app-linux.tar.gz
