ARG REPOSITORY=docker/app
ARG VERSION=0.5.0
ARG FILE_SHA256SUM=20e950ed94f818db3ca448dbb079a6ea6d913741740bf8568171fe4c0ac8f5fd
ENV FILE_URL https://github.com/${REPOSITORY}/releases/download/v${VERSION}/docker-app-linux.tar.gz
