ARG REPOSITORY=docker/app
ARG VERSION=0.3.0
ARG FILE_SHA256SUM=f9fcc65efbb37ace2195764200ec414ff24c87f566a0a480cd3215ee7069bb3b
ENV FILE_URL https://github.com/${REPOSITORY}/releases/download/v${VERSION}/docker-app-linux.tar.gz
