ARG REPOSITORY=docker/compose
ARG VERSION=1.20.1
ARG FILE_SHA256SUM=11a6923c2a589b946598fe205c8f645e57f3f4ee153d3b7315b7e1993c1b2ad1
ENV FILE_URL https://github.com/${REPOSITORY}/releases/download/${VERSION}/docker-compose-Linux-x86_64
