ARG REPOSITORY=docker/compose
ARG VERSION=1.17.1
ARG FILE_SHA256SUM=db0a7b79d195dc021461d5628a8d53eeb2e556d2548b764770fccabb0a319dd8
ENV FILE_URL https://github.com/${REPOSITORY}/releases/download/${VERSION}/docker-compose-Linux-x86_64
