ARG REPOSITORY=docker/compose
ARG VERSION=1.25.4
ARG FILE_SHA256SUM=542e93b1d5106d2769b325f60ba9a0ba087bb96e30dc2c1cb026f0cb642e9aed
ENV FILE_URL https://github.com/${REPOSITORY}/releases/download/${VERSION}/docker-compose-Linux-x86_64
