ARG REPOSITORY=github/hub
ARG VERSION=2.7.0
ARG FILE_SHA256SUM=007a5aca10fff7fa4db0f1e6231ab9ac508c5f9bc812f7985c07fcabfbe58dca
ENV FILE_URL https://github.com/${REPOSITORY}/releases/download/v${VERSION}/hub-linux-amd64-${VERSION}.tgz
ENV TAG_STRIP v
