ARG REPOSITORY=github/hub
ARG VERSION=2.5.1
ARG FILE_SHA256SUM=eee7cb455e1ab34aa3b1eb4afe0f44a31af70cf4d3289fad4e124c7c0cc7016d
ENV FILE_URL https://github.com/${REPOSITORY}/releases/download/v${VERSION}/hub-linux-amd64-${VERSION}.tgz
ENV TAG_STRIP v
